//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_EmployeeEntities : DbContext
    {
        public DB_EmployeeEntities()
            : base("name=DB_EmployeeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Educational_Details> tbl_Educational_Details { get; set; }
        public virtual DbSet<tbl_Employee_Master> tbl_Employee_Master { get; set; }
        public virtual DbSet<tbl_Error_Log> tbl_Error_Log { get; set; }
        public virtual DbSet<tbl_User_Master> tbl_User_Master { get; set; }
    
        public virtual int Proc_tbl_Employee_Master_Insert_Data(string employee_Name, string contact_No, string email, string address1, string address2, string city, string state, string country, string zipcode)
        {
            var employee_NameParameter = employee_Name != null ?
                new ObjectParameter("Employee_Name", employee_Name) :
                new ObjectParameter("Employee_Name", typeof(string));
    
            var contact_NoParameter = contact_No != null ?
                new ObjectParameter("Contact_No", contact_No) :
                new ObjectParameter("Contact_No", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var address1Parameter = address1 != null ?
                new ObjectParameter("Address1", address1) :
                new ObjectParameter("Address1", typeof(string));
    
            var address2Parameter = address2 != null ?
                new ObjectParameter("Address2", address2) :
                new ObjectParameter("Address2", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("Country", country) :
                new ObjectParameter("Country", typeof(string));
    
            var zipcodeParameter = zipcode != null ?
                new ObjectParameter("Zipcode", zipcode) :
                new ObjectParameter("Zipcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_tbl_Employee_Master_Insert_Data", employee_NameParameter, contact_NoParameter, emailParameter, address1Parameter, address2Parameter, cityParameter, stateParameter, countryParameter, zipcodeParameter);
        }
    
        public virtual ObjectResult<Proc_tbl_Employee_Master_Select_All_Result> Proc_tbl_Employee_Master_Select_All()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_tbl_Employee_Master_Select_All_Result>("Proc_tbl_Employee_Master_Select_All");
        }
    
        public virtual ObjectResult<Proc_tbl_Employee_Master_Select_By_Id_Result> Proc_tbl_Employee_Master_Select_By_Id(Nullable<int> employee_Id)
        {
            var employee_IdParameter = employee_Id.HasValue ?
                new ObjectParameter("Employee_Id", employee_Id) :
                new ObjectParameter("Employee_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Proc_tbl_Employee_Master_Select_By_Id_Result>("Proc_tbl_Employee_Master_Select_By_Id", employee_IdParameter);
        }
    
        public virtual int Proc_tbl_Employee_Master_Update_Data(Nullable<int> employee_Id, string employee_Name, string contact_No, string email, string address1, string address2, string city, string state, string country, string zipcode)
        {
            var employee_IdParameter = employee_Id.HasValue ?
                new ObjectParameter("Employee_Id", employee_Id) :
                new ObjectParameter("Employee_Id", typeof(int));
    
            var employee_NameParameter = employee_Name != null ?
                new ObjectParameter("Employee_Name", employee_Name) :
                new ObjectParameter("Employee_Name", typeof(string));
    
            var contact_NoParameter = contact_No != null ?
                new ObjectParameter("Contact_No", contact_No) :
                new ObjectParameter("Contact_No", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var address1Parameter = address1 != null ?
                new ObjectParameter("Address1", address1) :
                new ObjectParameter("Address1", typeof(string));
    
            var address2Parameter = address2 != null ?
                new ObjectParameter("Address2", address2) :
                new ObjectParameter("Address2", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("Country", country) :
                new ObjectParameter("Country", typeof(string));
    
            var zipcodeParameter = zipcode != null ?
                new ObjectParameter("Zipcode", zipcode) :
                new ObjectParameter("Zipcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_tbl_Employee_Master_Update_Data", employee_IdParameter, employee_NameParameter, contact_NoParameter, emailParameter, address1Parameter, address2Parameter, cityParameter, stateParameter, countryParameter, zipcodeParameter);
        }
    
        public virtual int Proc_tbl_Employee_Master_Update_Status(Nullable<int> employee_Id, Nullable<bool> status)
        {
            var employee_IdParameter = employee_Id.HasValue ?
                new ObjectParameter("Employee_Id", employee_Id) :
                new ObjectParameter("Employee_Id", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("status", status) :
                new ObjectParameter("status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Proc_tbl_Employee_Master_Update_Status", employee_IdParameter, statusParameter);
        }
    }
}
