//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Error_Log
    {
        public int Error_Id { get; set; }
        public string Page_Name { get; set; }
        public string Merthod_Name { get; set; }
        public string Error_Message { get; set; }
        public string Stack_Trace { get; set; }
        public System.DateTime Create_Datetime { get; set; }
    }
}
